CREATE TABLE contests (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  creator INTEGER NOT NULL,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  max_submissions INTEGER DEFAULT 10 NOT NULL,
  official BOOLEAN DEFAULT FALSE NOT NULL,
  status INTEGER DEFAULT 1 NOT NULL,
  winner_1 INTEGER,
  winner_2 INTEGER,
  winner_3 INTEGER
);